### ISSUE TITLE
Add ADRs into the repository

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#120]
We have made a lot of technical decisions, which unfortunately are not documented anywhere.?

We should add an ADR template into the repository and start documenting the ADR's

https://adr.github.io/

As part of this issue I will import the template and write up a few of the decisions I know about.

**TODO**
- [x] Import ADR template
- [x] Why flutter
- [x] Flutter beta channel
- [x] Embed content in the app, to support offline mode

**Comment by workerbee22** [comment]
As discussed @lukesleeman I'm starting to add a couple of extra app wide/architectural issues that go across the whole app. Goal is to make the code and architecture a little more consistent. As those get discussed and agreed, will add them to the ADR 👍
