### ISSUE TITLE
Make app GDPR compliant + better inform our users about what data is gathered

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#241]
As part of issue #15 we now gather analytics and crash reporting data using google analytics.  After[ researching the issues](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/241#issuecomment-620568108), I believe there are 4 things we need to do:

- [x] #301 -  Build a settings screen, under the info icon, that Clearly explains what data we gather, what its used for and provides a switch that disables analytics and Sentry.
- [x] #237 - Modify the disclaimer, so that under the "Please keep in mind section" it says: "WAC19 gathers analytics and crash data which is used to improve the app. For more information and to opt out, go to information > settings"
- [x] #300  -  Fill out the GDPR section in the firebase project and the DPA section in sentry.
- [x] Review the [WH privacy policy ](http://www.westernhealth.org.au/PatientsandVisitors/Medical_Records/Pages/default.aspx)(which we link to on the play and app stores) and make sure we comply with it

This issue will be used to coordinate the overall process, however I will fork out seperate issues where appropriate.

**Comment by workerbee22** [comment]
Yep one slight complication is that some of the testers are in the UK, although app at the moment is restricted to Australia in Google Play and App Store Connect.

**Comment by workerbee22** [comment]
Not there is a GDPR set of questions in Firebase we'll have to complete too.

**Comment by lukesleeman** [comment]
I'm guessing for the public release we are going to go global?  So I'm guessing we will need this?

Hopefully its just some questions we can answer and options we can turn on?

**Comment by lukesleeman** [comment]
During our call we agreed that I would try and progress this one, hopefully with @maks helping out 👍

**Comment by workerbee22** [comment]
Firebase project GDPR sectio we need to complete is this. So unless Western Health has an existing Privacy Officer, then suggest @greggmiller is best placed to be the nominated person?

![image](https://user-images.githubusercontent.com/5154664/80454958-39f53300-896e-11ea-8b47-80612abae315.png)

**Comment by lukesleeman** [comment]
It seems for sentry somebody needs to login and accept something called the DPA:
https://sentry.io/security/

> If you are a Sentry user, you can find the DPA under the Legal & Compliance section of your home page within the Sentry app. Complete it by:
>
> 
> - Reviewing and accepting the DPA itself
> - Adding your designated EU Representative’s info
> - Adding your designated Data Protection Officer’s information
> - Double-checking your company details (specifically, the legal name of your business)

**Comment by lukesleeman** [comment]
# Summary
So, after doing a bunch of research, I believe the following approach should be suitable:

1. Build a settings screen, under the info icon, that:
   a. Clearly explains what data we gather and why.
   b. Provides a switch that disables analytics and Sentry.
2. Modify the disclaimer, so that under the "Please keep in mind section" it says: "WAC19 gathers analytics and crash data which is used to improve the app.  For more information and to opt out, go to information > settings" .  How to turn of analytics in flutter firebase analytics is [explained in this issue](https://github.com/FirebaseExtended/flutterfire/issues/827)
3. Fill out the GDPR section in the firebase project and the DPA section in sentry.

Based off our reading we believe that will both cover our obligations under the GDRP and is inline with what other apps (such as the open source google IO app) do.

# More info

Unfortunately the there is a large amount of conflicting and vague information on the internet about what is needed to comply with the GDPR.  There was a lot of speculation before it came into force which still ranks highly in search results.  In addition a lot of information relates to websites (Which have no legal disclaimer users need to accept to access them) who use cookies to serve up ads (Which we don't do!) - reliable info relating to apps harder to find.

The following stack overflow answer comes from somebody working for a startup which generates privacy policies and provides SDKs for user consent and actually seems informed and useful:
https://stackoverflow.com/a/45996825

It points out googles EU user consent policy, which seems to have changed quite a bit since the stack overflow answer was written:
https://www.google.com/about/company/user-consent-policy/
https://www.google.com/about/company/user-consent-policy-help/

The policy seems to mainly relate to Ads, which we don't use, but it does have some guidelines that may still be helpful, if we consider the "best practises", even if they don't necessarily apply to us.

> You must obtain end users’ legally valid consent to:
> - the use of cookies or other local storage where legally required; and
> - the collection, sharing, and use of personal data for personalization of ads.
> When seeking consent you must:
> - retain records of consent given by end users; and
> - provide end users with clear instructions for revocation of consent.

I believe accepting the disclaimer & conditions of use which states we use analytics and crash reporting obtains our end users legally valid consent.  The app records when the disclaimer was agreed to, and consent will be revokable by toggling off analytics and crash reporting via settings

The policy mentions Ads and personalised adds a lot, which we don't use.  The question arises of do we even include record any personally identifiable information?  Google analytics allows you to associate data with a users ID - eg, something they use to login
https://support.google.com/analytics/answer/9213390

We are not using this setting:
![image](https://user-images.githubusercontent.com/902252/80485830-74c28f80-899d-11ea-98b5-90223c69d6a3.png)

With this turned off, an app install ID will be generated, which cannot be linked back to a user and changes if they un-install and re-install the app.  This is not considered personally identifiable information by google:
https://support.google.com/analytics/answer/7686480?hl=en

Any analytics data we provide won't be used for ad tracking, or sent to doubleclick.  These are our current sharing settings
![image](https://user-images.githubusercontent.com/902252/80483474-80ac5280-8999-11ea-83bb-c37c27681063.png)

**Comment by lukesleeman** [comment]
✅ I've reviewed the privacy policy on the WH website, which we comply with.

**Comment by maks** [comment]
Excellent job @lukesleeman !
Likewise for Sentry error reporting we are not collecting or sending any user personally identifiable information and only limited device information as can be seen here:

![Screenshot from 2020-04-29 08-15-34](https://user-images.githubusercontent.com/71999/80543292-ecbaa500-89f1-11ea-9b9c-31634ecc87a0.png)

**Comment by greggmiller** [comment]
I think this is now complete @lukesleeman ? Can we close it?

**Comment by lukesleeman** [comment]
> I think this is now complete @lukesleeman ? Can we close it?

Not quite - just waiting for @workerbee22 's PR to be merged, then we can close this one

**Comment by workerbee22** [comment]
[#301](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/301) closed now, although there are some loose end tasks to do later.

@lukesleeman we can probably close this now as functionally complete. Loose ends are just implementation/code cleanups.

**Comment by lukesleeman** [comment]
Closing this issue 🙌
